import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import localFont from "next/font/local";

const minecraft = localFont({
  src: "../../public/fonts/MinecraftTen-VGORe.ttf",
  variable: "--font-minecraft",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "my website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${minecraft.variable}`}>{children}</body>
    </html>
  );
}
